import json
from hashlib import sha512

from Crypto.Util.number import getPrime, getRandomRange, getRandomNBitInteger, long_to_bytes
from Crypto.Util.Padding import pad, unpad
from Crypto.Cipher import AES

#copied from question
def decrypt(iv: str, ct: str, key: int):
    iv = bytes.fromhex(iv); ct = bytes.fromhex(ct)
    key = long_to_bytes(key)
    key = sha512(key).digest()[:16]
    cipher = AES.new(key, AES.MODE_CBC, iv)
    ct = unpad(cipher.decrypt(ct), 16)
    return ct

priv = getPrime(512) #our random num


#To Alice
aliceHandshake = json.loads(input("Enter Alice handshake:")) 

#just reuse the g and n generated by Alice
g = aliceHandshake["g"]
n = aliceHandshake["n"]
aliceKey = pow(aliceHandshake["pub"], priv, n)

handShake = {"g" : g, "n" : n, "pub" : pow(g, priv, n)}

print("Send this to Bob and Alice:\n" + json.dumps(handShake))

bobHandshake = json.loads(input("Enter Bob handshake:"))
bobKey = pow(bobHandshake["pub"], priv, n)

#Decrypt Alice
aliceCipher = json.loads(input("Enter Alice's encrypted message:"))

firstHalf = decrypt(aliceCipher["iv"], aliceCipher["ciphertext"], aliceKey)

#Decrypt Bob
bobCipher = json.loads(input("Enter Bob's encrypted message:"))

secondHalf = decrypt(bobCipher["iv"], bobCipher["ciphertext"], bobKey)

print("The flag is: " + firstHalf.decode() + secondHalf.decode())

